[config]
; 请不要修改此处。请不要使用配置文件注释项来记录信息，软件加载时会强制覆盖删除。
version=1.4.0

[network]
; 软件访问的nga域名。默认值 https://bbs.nga.cn
base_url=https://stage1st.com
; 浏览器User-Agent，通常来说填写你常用浏览器的UA即可。修改时请将 两个尖括号及内部所有文本 均替换删除修改，且确保值是被反引号所包裹。
ua=`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:139.0) Gecko/20100101 Firefox/139.0`
; s1账号。修改时请将 两个尖括号及内部所有文本 均替换删除修改，且确保值是被反引号所包裹。不修改就会以匿名状态爬取帖子
username=`<MODIFY_ME>`
; s1密码。修改时请将 两个尖括号及内部所有文本 均替换删除修改，且确保值是被反引号所包裹。
password=`<MODIFY_ME>`
; 网络并发数，提高理论上可以增加下载速度。仅支持1、2、3。若开启enhance_ori_reply，请将此值设定为1。默认值2。建议设置为1不要改
thread=2
; [#56]每次下载限制新下载的大约页数。到上限后需要重新运行程序再追加下载，如此直至全部下载成功。允许范围-1（含）至100（含）。值为0或-1时则不限制。默认值100（约100页）。
page_download_limit=-1

[post]
; [#21]文件夹名是否包含标题。默认值True。修改后仅对全新拉取的tid生效。如果要使用Listupdate必须是True
use_title_as_folder_name=True
; [#21]Markdown 文件名是否为标题。默认值False。修改后仅对全新拉取的tid生效。
use_title_as_md_file_name=False
